server:
  port: 9000
security:
  sessions: NEVER
logging:
  level:
    org.springframework:
      security: DEBUG
      session: TRACE
spring:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user